Audits: {Avg Ball Time: '0:26', Avg Extra Balls: 0, Avg Game Time: '3:17', Avg Score: 2318634,
  Balls Played: 39, Games Played: 13, Games Started: 153}
ClassicHighScores:
- {inits: GSS, score: 500}
- {inits: ASP, score: 400}
- {inits: JRP, score: 300}
- {inits: JAG, score: 200}
- {inits: JTW, score: 100}
LoopsHighScoreData:
- {inits: GSS, score: 5}
